/* Données des 5 nouveaux jeux, par thème. */
window.GDATA = {
  /* ── DUEL DE CULTURE : questions à choix multiple (4 options, index 0 = bonne réponse avant mélange) ── */
  quizduel: {
    lol: [
      { q:"De quelle région vient Garen ?", a:["Demacia","Noxus","Ionia","Freljord"] },
      { q:"Combien de queues possède Ahri ?", a:["Neuf","Trois","Sept","Cinq"] },
      { q:"Quel objet lance Blitzcrank pour attraper un ennemi ?", a:["Sa main-fusée","Un filet","Une chaîne","Un harpon"] },
      { q:"Qui est le frère de Yasuo ?", a:["Yone","Zed","Kayn","Shen"] },
      { q:"Quel monstre neutre géant donne un bonus d'équipe majeur ?", a:["Le Baron Nashor","Le Drake","Le Golem","Le Krug"] },
      { q:"De quelle couleur est Amumu ?", a:["Vert","Bleu","Marron","Gris"] },
      { q:"Quelle championne est la sœur de Vi ?", a:["Jinx","Caitlyn","Camille","Sivir"] },
      { q:"Comment s'appelle la carte principale de LoL ?", a:["La Faille de l'invocateur","L'Abîme hurlant","Le Gouffre","L'Arène"] },
      { q:"Quel sort d'invocateur permet de se téléporter sur une courte distance ?", a:["Flash","Ghost","Teleport","Ignite"] },
      { q:"Nasus a une tête de quel animal ?", a:["Chacal","Lion","Loup","Chien"] },
      { q:"Quelle championne manie la lumière et est la sœur de Garen ?", a:["Lux","Lulu","Janna","Orianna"] },
      { q:"Combien de joueurs par équipe dans une partie classique ?", a:["Cinq","Trois","Quatre","Six"] },
      { q:"Quel champion est surnommé « la Main de Noxus » ?", a:["Darius","Draven","Swain","Sion"] },
      { q:"Zed est le maître de quel ordre ?", a:["L'Ordre des Ombres","L'Ordre du Kinkou","La Rose Noire","Les Immaculés"] },
      { q:"Quel est l'objectif à détruire pour gagner ?", a:["Le Nexus","La base","L'inhibiteur","Le cristal"] },
    ],
    pokemon: [
      { q:"Quel est le type de Salamèche ?", a:["Feu","Eau","Plante","Électrik"] },
      { q:"Combien de Pokémon dans la première génération ?", a:["151","150","251","100"] },
      { q:"Quelle est l'évolution finale de Carapuce ?", a:["Tortank","Carabaffe","Léviator","Flagadoss"] },
      { q:"De quel Pokémon Mewtwo est-il le clone ?", a:["Mew","Mewtwo","Deoxys","Celebi"] },
      { q:"Quel Pokémon accompagne Sacha partout ?", a:["Pikachu","Évoli","Salamèche","Bulbizarre"] },
      { q:"Quel objet sert à capturer les Pokémon ?", a:["La Pokéball","La Potion","Le Pokédex","La CT"] },
      { q:"En quoi évolue Magicarpe ?", a:["Léviator","Lokhlass","Hypocéan","Poissoroy"] },
      { q:"Quelle équipe de méchants suit Sacha ?", a:["La Team Rocket","La Team Aqua","La Team Magma","La Team Plasma"] },
      { q:"Quel type est super efficace contre l'Eau ?", a:["Plante","Feu","Vol","Roche"] },
      { q:"Combien de badges faut-il pour la Ligue de Kanto ?", a:["Huit","Six","Quatre","Dix"] },
      { q:"Quel Pokémon rose peut se transformer en n'importe quoi ?", a:["Métamorph","Mew","Rondoudou","Leveinard"] },
      { q:"Quelle ville est le point de départ dans Rouge/Bleu ?", a:["Bourg Palette","Argenta","Azuria","Carmin sur Mer"] },
      { q:"Quel oiseau légendaire est de type Électrik ?", a:["Électhor","Artikodin","Sulfura","Lugia"] },
      { q:"Quel type est insensible aux attaques Normal ?", a:["Spectre","Acier","Roche","Psy"] },
      { q:"Ectoplasma est de type Spectre et… ?", a:["Poison","Ténèbres","Vol","Psy"] },
    ],
    got: [
      { q:"Quelle maison a pour devise « Winter is coming » ?", a:["Stark","Lannister","Targaryen","Baratheon"] },
      { q:"Comment surnomme-t-on Daenerys ?", a:["Mère des Dragons","Reine des Épines","Main du Roi","Briseuse de Rois"] },
      { q:"Qui tue le Roi de la Nuit ?", a:["Arya","Jon Snow","Bran","Daenerys"] },
      { q:"Quel est le seul mot que dit Hodor ?", a:["Hodor","Winterfell","Non","Bran"] },
      { q:"Comment s'appelle le loup géant de Jon Snow ?", a:["Fantôme","Vent Gris","Été","Nymeria"] },
      { q:"Quelle famille vit à Port-Réal sur le Trône de Fer ?", a:["Lannister","Stark","Tully","Martell"] },
      { q:"De quoi est fait le Mur qui protège le Nord ?", a:["De glace","De pierre","De bois","D'acier"] },
      { q:"Qui est le jumeau de Cersei ?", a:["Jaime","Tyrion","Tywin","Joffrey"] },
      { q:"Quel métal peut tuer les Marcheurs Blancs ?", a:["Le verredragon","L'acier valyrien","L'or","Le fer"] },
      { q:"Comment s'appelle l'épée d'Arya ?", a:["Aiguille","Grand-Griffe","Glace","Feu"] },
      { q:"Quelle maison a un dragon pour emblème ?", a:["Targaryen","Stark","Baratheon","Greyjoy"] },
      { q:"Qui pousse Bran par la fenêtre au tout début ?", a:["Jaime","Le Limier","Ramsay","Theon"] },
      { q:"Quel personnage est appelé « Littlefinger » ?", a:["Petyr Baelish","Varys","Qyburn","Pycelle"] },
      { q:"De quelle région viennent les Dothraki ?", a:["Essos","Westeros","Dorne","Le Nord"] },
      { q:"Quel événement sanglant tue Robb et Catelyn Stark ?", a:["Les Noces Pourpres","La Bataille des Bâtards","Le Blackwater","La Longue Nuit"] },
    ],
    general: [
      { q:"Quelle est la capitale de la France ?", a:["Paris","Lyon","Marseille","Bordeaux"] },
      { q:"Qui a peint la Joconde ?", a:["Léonard de Vinci","Picasso","Van Gogh","Michel-Ange"] },
      { q:"Combien de continents y a-t-il sur Terre ?", a:["Sept","Cinq","Six","Huit"] },
      { q:"En quelle année a coulé le Titanic ?", a:["1912","1905","1920","1898"] },
      { q:"Quelle planète est la plus proche du Soleil ?", a:["Mercure","Vénus","Mars","Terre"] },
      { q:"Qui a écrit « Le Petit Prince » ?", a:["Saint-Exupéry","Victor Hugo","Molière","Zola"] },
      { q:"Quel est l'animal le plus rapide du monde ?", a:["Le faucon pèlerin","Le guépard","Le lièvre","Le cheval"] },
      { q:"Combien de côtés a un hexagone ?", a:["Six","Cinq","Sept","Huit"] },
      { q:"Quel pays a offert la statue de la Liberté aux USA ?", a:["La France","L'Angleterre","L'Espagne","L'Italie"] },
      { q:"Quelle est la formule de l'eau ?", a:["H2O","CO2","O2","NaCl"] },
      { q:"Qui a dit « Je pense donc je suis » ?", a:["Descartes","Platon","Socrate","Kant"] },
      { q:"Quel est le plus grand océan ?", a:["Le Pacifique","L'Atlantique","L'Indien","L'Arctique"] },
      { q:"Combien de joueurs dans une équipe de football sur le terrain ?", a:["Onze","Neuf","Dix","Douze"] },
      { q:"Quel organe pompe le sang ?", a:["Le cœur","Le foie","Le poumon","Le rein"] },
      { q:"En quelle année l'homme a-t-il marché sur la Lune ?", a:["1969","1959","1975","1980"] },
    ],
  },

  /* ── PLUS OU MOINS : deux éléments, deviner lequel a la plus grande valeur (stat cachée) ── */
  higher: {
    lol: { unit:"de sortie (année)", items:[
      ["Ryze",2009],["Annie",2009],["Teemo",2009],["Garen",2010],["Lux",2011],["Fizz",2011],["Draven",2012],
      ["Jinx",2013],["Yasuo",2013],["Braum",2014],["Ekko",2015],["Kindred",2015],["Camille",2016],["Kayn",2017],
      ["Pyke",2018],["Neeko",2018],["Yuumi",2019],["Aphelios",2019],["Samira",2020],["Viego",2021],["Zeri",2022],
    ]},
    pokemon: { unit:"numéro au Pokédex", items:[
      ["Bulbizarre",1],["Pikachu",25],["Miaouss",52],["Onix",95],["Magicarpe",129],["Ronflex",143],["Mewtwo",150],
      ["Héricendre",155],["Pichu",172],["Lugia",249],["Arcko",252],["Gobou",258],["Métang",375],["Lucario",448],
      ["Pikachu Alola",25],["Vipélierre",495],["Amphinobi",658],["Flambino",653],["Miaouss de Galar",52],
    ]},
    got: { unit:"popularité (nb de saisons présent, sur 8)", items:[
      ["Jon Snow",8],["Tyrion",8],["Cersei",8],["Daenerys",8],["Arya",8],["Sansa",8],["Bran",8],["Jaime",8],
      ["Ned Stark",1],["Robb Stark",3],["Joffrey",4],["Oberyn",1],["Khal Drogo",1],["Hodor",6],["Ygrid",4],
      ["Le Roi de la Nuit",6],["Brienne",7],["Theon",8],["Melisandre",8],
    ]},
    general: { unit:"année de sortie / naissance", items:[
      ["Mario (1er jeu)",1981],["Pac-Man",1980],["Tetris",1984],["Le Roi Lion (film)",1994],["Titanic (film)",1997],
      ["Harry Potter (1er livre)",1997],["Star Wars (1er film)",1977],["Minecraft",2011],["Fortnite",2017],
      ["Astérix (1re BD)",1959],["Tintin (1re BD)",1929],["Michael Jackson",1958],["Zidane",1972],["Mbappé",1998],
      ["Beyoncé",1981],["La Tour Eiffel",1889],["Internet grand public",1991],["Le premier iPhone",2007],
    ]},
  },

  /* ── ASSOCIATION : relier chaque élément à sa bonne catégorie (2 groupes) ── */
  match: {
    lol: { groups:["Demacia","Noxus"], pairs:[
      ["Garen","Demacia"],["Lux","Demacia"],["Jarvan IV","Demacia"],["Shyvana","Demacia"],["Fiora","Demacia"],
      ["Darius","Noxus"],["Draven","Noxus"],["Katarina","Noxus"],["Swain","Noxus"],["Cassiopeia","Noxus"],
    ]},
    pokemon: { groups:["Type Feu","Type Eau"], pairs:[
      ["Salamèche","Type Feu"],["Dracaufeu","Type Feu"],["Goupix","Type Feu"],["Caninos","Type Feu"],["Ponyta","Type Feu"],
      ["Carapuce","Type Eau"],["Tortank","Type Eau"],["Magicarpe","Type Eau"],["Stari","Type Eau"],["Tentacool","Type Eau"],
    ]},
    got: { groups:["Maison Stark","Maison Lannister"], pairs:[
      ["Jon Snow","Maison Stark"],["Arya","Maison Stark"],["Sansa","Maison Stark"],["Bran","Maison Stark"],["Ned","Maison Stark"],
      ["Cersei","Maison Lannister"],["Jaime","Maison Lannister"],["Tyrion","Maison Lannister"],["Tywin","Maison Lannister"],["Joffrey","Maison Lannister"],
    ]},
    general: { groups:["Marvel","DC Comics"], pairs:[
      ["Iron Man","Marvel"],["Spider-Man","Marvel"],["Thor","Marvel"],["Hulk","Marvel"],["Captain America","Marvel"],
      ["Batman","DC Comics"],["Superman","DC Comics"],["Wonder Woman","DC Comics"],["Flash","DC Comics"],["Aquaman","DC Comics"],
    ]},
  },

  /* ── VRAI OU FAUX : affirmations, true = vrai ── */
  truefalse: {
    lol: [
      ["Teemo est un yordle.",true],["Garen vient de Noxus.",false],["Yasuo et Yone sont frères.",true],
      ["Le Baron Nashor donne un bonus à toute l'équipe.",true],["Ahri a sept queues.",false],
      ["Le but du jeu est de détruire le Nexus adverse.",true],["Amumu est une momie.",true],
      ["Jinx est la sœur de Caitlyn.",false],["Nasus a une tête de chacal.",true],["Il y a 6 joueurs par équipe.",false],
      ["Darius est surnommé la Main de Noxus.",true],["Zed maîtrise la lumière.",false],["Lux est la sœur de Garen.",true],
      ["Le Flash est un objet.",false],["Thresh collectionne les âmes.",true],
    ],
    pokemon: [
      ["Pikachu est de type Électrik.",true],["Salamèche est de type Eau.",false],["Mewtwo est un clone de Mew.",true],
      ["Il y a 151 Pokémon dans la 1re génération.",true],["Magicarpe évolue en Léviator.",true],
      ["Le type Feu est fort contre l'Eau.",false],["La Team Rocket veut protéger les Pokémon.",false],
      ["Métamorph peut se transformer.",true],["Carapuce est un starter.",true],["Ectoplasma est de type Feu.",false],
      ["Ondine possède un Psykokwak.",true],["Il faut 8 badges pour la Ligue de Kanto.",true],
      ["Évoli n'a qu'une seule évolution.",false],["Onix est de type Roche et Sol.",true],["Rondoudou endort avec son chant.",true],
    ],
    got: [
      ["La devise des Stark est « Winter is coming ».",true],["Cersei est la sœur de Jon Snow.",false],
      ["Arya tue le Roi de la Nuit.",true],["Hodor ne dit qu'un seul mot.",true],["Le Mur est fait de pierre.",false],
      ["Daenerys est la Mère des Dragons.",true],["Jaime et Cersei sont jumeaux.",true],
      ["Le verredragon tue les Marcheurs Blancs.",true],["Ned Stark survit jusqu'à la fin.",false],
      ["Les Dothraki viennent d'Essos.",true],["Tyrion est un Lannister.",true],["Le loup de Jon s'appelle Été.",false],
      ["Les Noces Pourpres tuent Robb Stark.",true],["Theon a été élevé par les Lannister.",false],["Bran devient roi à la fin.",true],
    ],
    general: [
      ["La capitale de la France est Paris.",true],["Le Titanic a coulé en 1912.",true],
      ["La Joconde a été peinte par Picasso.",false],["Il y a 7 continents.",true],["Mercure est la planète la plus proche du Soleil.",true],
      ["L'eau a pour formule CO2.",false],["Le guépard est l'animal le plus rapide du monde.",false],
      ["L'homme a marché sur la Lune en 1969.",true],["Un hexagone a 6 côtés.",true],["Napoléon est né en Corse.",true],
      ["Astérix boit une potion magique.",true],["Le cœur pompe le sang.",true],["Shrek est un dragon.",false],
      ["La Tour Eiffel est en fer.",true],["Einstein a créé la théorie de la relativité.",true],
    ],
  },

  /* ── LE MENTEUR : 3 affirmations, une seule est fausse (index de l'intrus) ── */
  liar: {
    lol: [
      { s:["Teemo est un yordle.","Teemo pose des champignons.","Teemo vient de Noxus."], lie:2 },
      { s:["Garen vient de Demacia.","Garen tourne sur lui-même.","Garen lance des haches."], lie:2 },
      { s:["Ahri est une renarde.","Ahri charme ses ennemis.","Ahri a cinq queues."], lie:2 },
      { s:["Yasuo maîtrise le vent.","Yasuo est le frère de Zed.","Yasuo a été accusé à tort."], lie:1 },
      { s:["Le Nexus est l'objectif final.","Il y a 5 joueurs par équipe.","Le Baron est un allié."], lie:2 },
      { s:["Darius vient de Noxus.","Darius a une guillotine.","Darius est un yordle."], lie:2 },
      { s:["Lux manie la lumière.","Lux est la sœur de Garen.","Lux vient de Noxus."], lie:2 },
      { s:["Blitzcrank est un robot.","Blitzcrank attrape avec sa main.","Blitzcrank vient de Demacia."], lie:2 },
      { s:["Jinx adore les explosions.","Jinx vient de Zaun.","Jinx est très calme."], lie:2 },
      { s:["Nasus a une tête de chacal.","Nasus est très jeune.","Nasus vient de Shurima."], lie:1 },
    ],
    pokemon: [
      { s:["Pikachu est de type Électrik.","Pikachu est jaune.","Pikachu évolue en Raichu par échange."], lie:2 },
      { s:["Salamèche est un starter.","Salamèche est de type Feu.","Salamèche évolue en Tortank."], lie:2 },
      { s:["Mewtwo est un clone.","Mewtwo est de type Psy.","Mewtwo a été trouvé dans un volcan."], lie:2 },
      { s:["Magicarpe est réputé inutile.","Magicarpe évolue en Léviator.","Magicarpe est de type Vol."], lie:2 },
      { s:["Ectoplasma est violet.","Ectoplasma est de type Plante.","Ectoplasma fait des farces."], lie:1 },
      { s:["La Pokéball sert à capturer.","Il y a 151 Pokémon en Gén 1.","La Team Rocket protège les Pokémon."], lie:2 },
      { s:["Ronflex est gros.","Ronflex dort beaucoup.","Ronflex est de type Eau."], lie:2 },
      { s:["Évoli a plusieurs évolutions.","Évoli est de type Feu.","Aquali évolue d'Évoli."], lie:1 },
      { s:["Miaouss aime les objets brillants.","Miaouss suit la Team Rocket.","Miaouss est un chien."], lie:2 },
      { s:["Onix est un serpent de pierre.","Onix appartient à Pierre.","Onix est de type Feu."], lie:2 },
    ],
    got: [
      { s:["Jon Snow vient du Nord.","Son loup s'appelle Fantôme.","Il est un Lannister."], lie:2 },
      { s:["Daenerys a des dragons.","Elle vient de Winterfell.","Le feu ne la brûle pas."], lie:1 },
      { s:["Tyrion est un Lannister.","Tyrion est très intelligent.","Tyrion est un géant."], lie:2 },
      { s:["Arya a une épée nommée Aiguille.","Arya tue le Roi de la Nuit.","Arya rêve d'être une lady."], lie:2 },
      { s:["Hodor ne dit qu'un mot.","Hodor porte Bran.","Hodor est tout petit."], lie:2 },
      { s:["Cersei aime le vin.","Cersei est reine.","Cersei déteste Jaime."], lie:2 },
      { s:["Le Mur est fait de glace.","Le verredragon tue les Marcheurs.","Ned Stark survit à la série."], lie:2 },
      { s:["Les Stark vivent à Winterfell.","Leur devise est Winter is coming.","Leur emblème est un dragon."], lie:2 },
      { s:["Joffrey est cruel.","Joffrey est aimé de tous.","Joffrey est blond."], lie:1 },
      { s:["Les Dothraki sont des cavaliers.","Ils viennent d'Essos.","Ils vivent sur le Mur."], lie:2 },
    ],
    general: [
      { s:["La Joconde est au Louvre.","Elle a été peinte par De Vinci.","Elle représente un homme."], lie:2 },
      { s:["Le Titanic a coulé en 1912.","Un iceberg l'a coulé.","Il était tout petit."], lie:2 },
      { s:["Napoléon est né en Corse.","Il fut empereur.","Il était très grand."], lie:2 },
      { s:["La Terre a 7 continents.","Le Pacifique est le plus grand océan.","Le Soleil tourne autour de la Terre."], lie:2 },
      { s:["Astérix est gaulois.","Il boit une potion magique.","Il est très grand et fort."], lie:2 },
      { s:["Einstein a les cheveux en bataille.","Il a créé la relativité.","Il était peintre."], lie:2 },
      { s:["Batman protège Gotham.","Batman a des super-pouvoirs.","Batman est riche."], lie:1 },
      { s:["L'eau est H2O.","Le cœur pompe le sang.","Un carré a 3 côtés."], lie:2 },
      { s:["L'homme a marché sur la Lune.","C'était en 1969.","C'était Christophe Colomb."], lie:2 },
      { s:["Le guépard est rapide.","Le faucon pèlerin est le plus rapide.","La tortue est le plus rapide."], lie:2 },
    ],
  },
};
