/* Contenu des 4 thèmes pour les 3 jeux. Ajouter un thème = une entrée dans chaque section. */
window.THEMES = {
  meta: {
    lol:     { label: "League of Legends", emoji: "⚔️" },
    pokemon: { label: "Pokémon",           emoji: "🔴" },
    got:     { label: "Game of Thrones",   emoji: "🐉" },
    general: { label: "Général",           emoji: "🎲" },
  },

  /* ── QUI EST-CE : pools de personnages. img: fonction optionnelle id→url ── */
  quiestce: {
    lol: {
      img: id => `https://ddragon.leagueoflegends.com/cdn/16.14.1/img/champion/${id.replace(/[^A-Za-z]/g,"")}.png`,
      chars: ["Ahri","Akali","Amumu","Annie","Ashe","Blitzcrank","Braum","Caitlyn","Camille","Darius","Diana","Draven",
        "Ekko","Elise","Ezreal","Fiora","Fizz","Galio","Garen","Gragas","Graves","Irelia","Ivern","Janna","Jax","Jayce",
        "Jhin","Jinx","Karma","Karthus","Katarina","Kayle","Kayn","Kennen","Leona","Lissandra","Lucian","Lulu","Lux",
        "Malphite","Malzahar","Maokai","Mordekaiser","Morgana","Nami","Nasus","Nautilus","Neeko","Nidalee","Nocturne",
        "Olaf","Orianna","Pantheon","Poppy","Pyke","Quinn","Rakan","Rammus","Rengar","Riven","Rumble","Ryze","Samira",
        "Sejuani","Senna","Seraphine","Shen","Shyvana","Singed","Sion","Sivir","Skarner","Sona","Soraka","Swain","Sylas",
        "Syndra","Talon","Taric","Teemo","Thresh","Tristana","Tryndamere","Twitch","Urgot","Varus","Vayne","Veigar","Vi",
        "Viego","Viktor","Vladimir","Volibear","Xayah","Xerath","Yasuo","Yone","Yorick","Yuumi","Zac","Zed","Ziggs",
        "Zilean","Zoe","Zyra"],
    },
    pokemon: {
      img: (id, i) => `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${i + 1}.png`,
      chars: ["Bulbizarre","Herbizarre","Florizarre","Salamèche","Reptincel","Dracaufeu","Carapuce","Carabaffe","Tortank",
        "Chenipan","Chrysacier","Papilusion","Aspicot","Coconfort","Dardargnan","Roucool","Roucoups","Roucarnage",
        "Rattata","Rattatac","Piafabec","Rapasdepic","Abo","Arbok","Pikachu","Raichu","Sabelette","Sablaireau",
        "Nidoran ♀","Nidorina","Nidoqueen","Nidoran ♂","Nidorino","Nidoking","Mélofée","Mélodelfe","Goupix","Feunard",
        "Rondoudou","Grodoudou","Nosferapti","Nosferalto","Mystherbe","Ortide","Rafflesia","Paras","Parasect","Mimitoss",
        "Aéromite","Taupiqueur","Triopikeur","Miaouss","Persian","Psykokwak","Akwakwak","Férosinge","Colossinge",
        "Caninos","Arcanin","Ptitard","Têtarte","Tartard","Abra","Kadabra","Alakazam","Machoc","Machopeur","Mackogneur",
        "Chétiflor","Boustiflor","Empiflor","Tentacool","Tentacruel","Racaillou","Gravalanch","Grolem","Ponyta","Galopa",
        "Ramoloss","Flagadoss","Magnéti","Magnéton","Canarticho","Doduo","Dodrio","Otaria","Lamantine","Tadmorv",
        "Grotadmorv","Kokiyas","Crustabri","Fantominus","Spectrum","Ectoplasma","Onix","Soporifik","Hypnomade","Krabby",
        "Krabboss","Voltorbe","Électrode","Noeunoeuf","Noadkoko","Osselait","Ossatueur","Kicklee","Tygnon","Excelangue",
        "Smogo","Smogogo","Rhinocorne","Rhinoféros","Leveinard","Saquedeneu","Kangourex","Hypotrempe","Hypocéan",
        "Poissirène","Poissoroy","Stari","Staross","M. Mime","Insécateur","Lippoutou","Élektek","Magmar","Scarabrute",
        "Tauros","Magicarpe","Léviator","Lokhlass","Métamorph","Évoli","Aquali","Voltali","Pyroli","Porygon","Amonita",
        "Amonistar","Kabuto","Kabutops","Ptéra","Ronflex","Artikodin","Électhor","Sulfura","Minidraco","Draco",
        "Dracolosse","Mewtwo","Mew"],
    },
    got: {
      img: null,
      chars: ["Jon Snow","Daenerys","Tyrion","Cersei","Jaime","Arya","Sansa","Bran","Ned Stark","Catelyn","Robb Stark",
        "Joffrey","Tommen","Stannis","Renly","Robert Baratheon","Melisandre","Davos","Brienne","Le Limier","La Montagne",
        "Littlefinger","Varys","Samwell","Jorah","Khal Drogo","Missandei","Ver Gris","Theon","Yara","Ramsay",
        "Roose Bolton","Tywin","Olenna","Margaery","Loras","Hodor","Gendry","Bronn","Podrick","Ygritte","Tormund",
        "Le Roi de la Nuit","Oberyn","Ellaria","Shae","Grand Mestre Pycelle","Qyburn","Euron","Beric"],
    },
    general: {
      img: null,
      chars: ["Batman","Superman","Spider-Man","Iron Man","Thor","Hulk","Wonder Woman","Harry Potter","Hermione",
        "Ron Weasley","Dumbledore","Voldemort","Gandalf","Frodon","Legolas","Dark Vador","Yoda","Luke Skywalker",
        "Han Solo","Shrek","L'Âne","Mario","Luigi","Sonic","Lara Croft","James Bond","Sherlock Holmes","Napoléon",
        "Cléopâtre","Einstein","Mbappé","Zidane","Beyoncé","Michael Jackson","Astérix","Obélix","Tintin","Lucky Luke",
        "Mickey","Donald","Homer Simpson","Bart Simpson","Bob l'éponge","Naruto","Goku","Luffy","Elsa","Simba",
        "Buzz l'Éclair","Woody","Jack Sparrow","Le Père Noël","Dracula","Mary Poppins","Indiana Jones","Rocky",
        "Terminator","Kirikou","Titeuf","Le Petit Prince"],
    },
  },

  /* ── IMPOSTEUR : paires de mots proches [commun possible, commun possible] ── */
  imposteur: {
    lol: [["Garen","Darius"],["Yasuo","Yone"],["Ahri","LeBlanc"],["Zed","Talon"],["Lux","Morgana"],["Jinx","Vi"],
      ["Ezreal","Lucian"],["Blitzcrank","Thresh"],["Teemo","Kennen"],["Ashe","Varus"],["Leona","Diana"],
      ["Nasus","Renekton"],["Katarina","Akali"],["Amumu","Annie"],["Braum","Taric"],["Soraka","Sona"],
      ["Baron Nashor","Drake"],["Jungle","Toplane"],["Faille de l'invocateur","ARAM"],["Flash","Ghost"]],
    pokemon: [["Pikachu","Raichu"],["Ectoplasma","Spectrum"],["Ronflex","Goinfrex"],["Évoli","Aquali"],
      ["Dracaufeu","Dracolosse"],["Magicarpe","Poissirène"],["Miaouss","Persian"],["Rondoudou","Grodoudou"],
      ["Mewtwo","Mew"],["Onix","Steelix"],["Salamèche","Héricendre"],["Carapuce","Tortank"],
      ["Artikodin","Électhor"],["Caninos","Arcanin"],["Pokéball","Masterball"],["Sacha","Ondine"],
      ["Team Rocket","Ligue Pokémon"],["Pokédex","Pokéball"],["Bourg Palette","Argenta"],["Badge","CT"]],
    got: [["Jon Snow","Robb Stark"],["Cersei","Margaery"],["Tyrion","Varys"],["Arya","Sansa"],
      ["La Montagne","Le Limier"],["Stannis","Renly"],["Stark","Lannister"],["Winterfell","Port-Réal"],
      ["Marcheurs Blancs","Sauvageons"],["Dothraki","Immaculés"],["Dragon","Loup géant"],["Le Mur","Le Trône de Fer"],
      ["Daenerys","Cersei"],["Jaime","Bronn"],["Mestre","Septon"],["Garde de Nuit","Garde Royale"],
      ["Valyria","Essos"],["Hodor","Ver Gris"],["Melisandre","Olenna"],["Baratheon","Targaryen"]],
    general: [["Café","Thé"],["Croissant","Pain au chocolat"],["Vélo","Trottinette"],["Plage","Piscine"],
      ["Chien","Chat"],["Pizza","Tacos"],["Ski","Snowboard"],["Métro","Bus"],["Star Wars","Star Trek"],
      ["Harry Potter","Le Seigneur des Anneaux"],["Titanic","Avatar"],["Breaking Bad","Narcos"],
      ["Friends","How I Met Your Mother"],["Le Roi Lion","Le Livre de la Jungle"],["Mario","Sonic"],
      ["Minecraft","Fortnite"],["Noël","Nouvel An"],["Boulanger","Pâtissier"],["Guitare","Piano"],["Lune","Soleil"]],
  },

  /* ── QUIZ MYSTÈRE : 5 indices du plus vague au plus précis, alt = réponses acceptées ── */
  quiz: {
    lol: [
      { name:"Teemo", alt:[], clues:["C'est un yordle.","Il porte un grand chapeau.","Tout le monde le déteste en face.","Il pose des champignons invisibles.","Le scout jaune de Bandle, cauchemar des toplaners."]},
      { name:"Yasuo", alt:[], clues:["C'est un épéiste.","Il vient d'Ionia.","Il a été accusé à tort d'un meurtre.","Son bouclier se recharge en bougeant et il maîtrise le vent.","Le samouraï exilé au mur de vent, frère de Yone."]},
      { name:"Jinx", alt:[], clues:["Elle vient de Zaun.","Elle est complètement folle.","Elle adore les explosions.","Sa sœur est une agente de Piltover.","La tireuse aux tresses bleues avec Pow-Pow et Fishbones."]},
      { name:"Thresh", alt:[], clues:["C'est un spectre.","Il vient des Îles Obscures.","Il collectionne les âmes dans sa lanterne.","Son crochet est redouté en botlane.","Le geôlier des âmes à la faux et à la lanterne."]},
      { name:"Lux", alt:["Luxanna"], clues:["Elle vient de Demacia.","Elle est très souriante.","Son frère est un grand soldat à la grosse épée.","Elle manie la lumière.","La mage lumineuse, sœur de Garen, au laser géant."]},
      { name:"Amumu", alt:[], clues:["Il est très triste.","C'est une momie.","Il cherche désespérément un ami.","Ses pleurs font des dégâts autour de lui.","La petite momie verte qui pleure, ultime en toile."]},
      { name:"Blitzcrank", alt:[], clues:["C'est un robot.","Il a été créé à Zaun.","Il est fait de vapeur et de métal.","Son bras se tend pour attraper les ennemis.","Le golem de vapeur doré au grab légendaire."]},
      { name:"Darius", alt:[], clues:["Il vient de Noxus.","C'est un général redouté.","Son frère lance des haches lui aussi.","Il saigne ses ennemis avant de les achever.","La Main de Noxus et sa guillotine dunk."]},
      { name:"Ahri", alt:[], clues:["Elle vient d'Ionia.","Elle a neuf queues.","Elle charme ses ennemis.","C'est une renarde qui absorbe l'essence vitale.","La renarde à neuf queues et son baiser charmeur."]},
      { name:"Ezreal", alt:[], clues:["C'est un explorateur.","Il vient de Piltover.","Il est très sûr de lui.","Son gantelet tire des projectiles magiques.","L'aventurier blond qui spamme son Q et blink partout."]},
      { name:"Yuumi", alt:[], clues:["C'est un familier magique.","Elle voyage sur un livre.","Elle s'attache à un allié.","Impossible de la cibler quand elle est fixée.","La chatte magique qui AFK sur son support."]},
      { name:"Garen", alt:[], clues:["Il vient de Demacia.","Il crie le nom de son royaume.","Sa sœur manie la lumière.","Il tourne sur lui-même avec sa grande épée.","Le soldat au E qui spin et à l'ultime justicier."]},
    ],
    pokemon: [
      { name:"Ronflex", alt:[], clues:["Type Normal.","Il est énorme et très lourd.","Il passe sa vie à manger et dormir.","Il bloque la route dans les jeux, il faut une flûte pour le réveiller.","Le gros dormeur bleu-vert au ventre crème."]},
      { name:"Ectoplasma", alt:[], clues:["Il est violet.","Type Spectre et Poison.","Il adore faire des farces effrayantes dans l'ombre.","C'est l'évolution finale de Fantominus.","Le fantôme au sourire immense et aux yeux rouges."]},
      { name:"Pikachu", alt:[], clues:["Type Électrik.","Il vit en groupe dans les forêts.","Ses joues stockent de l'électricité.","C'est le compagnon de Sacha dans le dessin animé.","La souris jaune, mascotte de la licence."]},
      { name:"Dracaufeu", alt:[], clues:["Il peut voler.","Type Feu.","La flamme de sa queue reflète sa vitalité.","C'est l'évolution finale d'un starter de Kanto.","Le dragon orange, starter feu de la première génération."]},
      { name:"Magicarpe", alt:[], clues:["Type Eau.","Il est réputé complètement inutile.","Il ne sait quasiment que faire Trempette.","Il évolue en un dragon marin redoutable.","Le poisson rouge et or qui saute partout."]},
      { name:"Léviator", alt:[], clues:["Il est immense.","Type Eau et Vol.","Il est connu pour sa rage destructrice.","Il évolue d'un Pokémon considéré comme le plus faible.","Le serpent de mer bleu issu de Magicarpe."]},
      { name:"Évoli", alt:[], clues:["Type Normal.","Son code génétique est instable.","Il peut évoluer de nombreuses façons différentes.","Ses évolutions incluent Aquali, Voltali et Pyroli.","Le petit renard marron aux multiples évolutions."]},
      { name:"Mewtwo", alt:[], clues:["Type Psy.","Il a été créé par des scientifiques.","C'est un clone surpuissant d'un Pokémon mythique.","On l'affronte dans une grotte après la Ligue.","Le clone légendaire de Mew."]},
      { name:"Psykokwak", alt:[], clues:["Type Eau.","Il a constamment mal à la tête.","Ses migraines libèrent des pouvoirs psychiques.","Dans le dessin animé, il sort sans arrêt de la Pokéball d'Ondine.","Le canard jaune qui se tient la tête."]},
      { name:"Rondoudou", alt:[], clues:["Il est rose.","Type Normal et Fée.","Sa voix endort quiconque l'écoute.","Il se venge en dessinant sur le visage des endormis.","La boule rose qui chante avec son micro-feutre."]},
      { name:"Métamorph", alt:["Metamorph"], clues:["Type Normal.","Il est rose et informe.","Il peut se transformer en n'importe quoi.","Il est très recherché pour la reproduction.","La flaque rose qui copie tous les Pokémon."]},
      { name:"Lokhlass", alt:[], clues:["Type Eau et Glace.","Il est d'une grande douceur.","Il transporte les gens sur son dos à travers les mers.","On l'utilise souvent comme Surf-taxi.","Le plésiosaure bleu à carapace grise."]},
    ],
    got: [
      { name:"Jon Snow", alt:["Jon"], clues:["Il vient du Nord.","On le dit bâtard.","Il rejoint la Garde de Nuit.","Son loup géant s'appelle Fantôme.","Le corbeau devenu roi du Nord, 'You know nothing…'"]},
      { name:"Tyrion", alt:["Tyrion Lannister"], clues:["Il est très intelligent.","Sa famille est la plus riche de Westeros.","Il boit et il sait des choses.","Son père le méprise, sa sœur le hait.","Le nain Lannister, Main de la Reine."]},
      { name:"Daenerys", alt:["Khaleesi","Dany"], clues:["Elle vient d'une dynastie déchue.","Elle traverse le Détroit depuis Essos.","Elle épouse un chef de guerre nomade.","Le feu ne la brûle pas.","La Mère des Dragons, Khaleesi."]},
      { name:"Arya", alt:["Arya Stark"], clues:["C'est une jeune fille du Nord.","Elle refuse d'être une lady.","Elle dresse une liste de noms.","Elle apprend auprès des Sans-Visage.","La petite Stark à l'épée Aiguille."]},
      { name:"Le Limier", alt:["Sandor","Sandor Clegane","Limier"], clues:["C'est un guerrier redoutable.","Il a peur du feu.","Son visage est à moitié brûlé.","Son frère est encore plus monstrueux que lui.","Sandor Clegane, protecteur bougon d'Arya."]},
      { name:"Hodor", alt:[], clues:["Il est immense et doux.","Il sert la famille Stark.","Il ne dit qu'un seul mot.","Il porte Bran sur son dos.","'Hold the door…'"]},
      { name:"Cersei", alt:["Cersei Lannister"], clues:["Elle est reine.","Elle aime le vin.","Elle aime son frère jumeau… beaucoup.","Elle fait exploser un septuaire entier.","La reine Lannister, mère de Joffrey."]},
      { name:"Jaime", alt:["Jaime Lannister"], clues:["C'est l'un des meilleurs épéistes du royaume.","On l'appelle un tueur de roi.","Il perd sa main d'épée.","Il pousse un enfant par une fenêtre.","Le Régicide, jumeau de Cersei."]},
      { name:"Ned Stark", alt:["Ned","Eddard","Eddard Stark"], clues:["Il est loyal et honorable.","Il gouverne le Nord.","Il devient Main du Roi malgré lui.","Son honneur lui coûte la tête dès la saison 1.","Le seigneur de Winterfell, père de la meute."]},
      { name:"Le Roi de la Nuit", alt:["Roi de la Nuit","Night King"], clues:["Il vient du Grand Nord.","Il ne parle jamais.","Il relève les morts.","Il tue un dragon d'un seul javelot.","Le chef des Marcheurs Blancs aux yeux bleus."]},
      { name:"Brienne", alt:["Brienne de Torth","Brienne de Tarth"], clues:["C'est une guerrière d'exception.","On se moque de son apparence.","Elle jure de protéger les filles Stark.","Elle est adoubée par Jaime.","La chevaleresse de Torth, fidèle entre toutes."]},
      { name:"Samwell", alt:["Sam","Samwell Tarly"], clues:["Il est peureux et maladroit.","Son père le renie.","Il rejoint la Garde de Nuit avec Jon.","Il tue un Marcheur Blanc avec du verredragon.","Le meilleur ami de Jon, apprenti mestre."]},
    ],
    general: [
      { name:"Le Père Noël", alt:["Père Noël","Papa Noël","Santa"], clues:["Il travaille une seule nuit par an.","Il est très généreux.","Il s'habille en rouge.","Il passe par la cheminée.","Ho ho ho, il vit au pôle Nord."]},
      { name:"La Joconde", alt:["Joconde","Mona Lisa"], clues:["Elle est italienne.","Elle est mondialement célèbre.","Son sourire est mystérieux.","Elle vit au Louvre.","Le tableau de Léonard de Vinci."]},
      { name:"Napoléon", alt:["Napoléon Bonaparte","Bonaparte"], clues:["Il est né en Corse.","Il devient empereur.","Il gagne Austerlitz.","Il finit exilé à Sainte-Hélène.","Le petit caporal au bicorne."]},
      { name:"Batman", alt:[], clues:["Il est très riche.","Il a perdu ses parents.","Il n'a aucun super-pouvoir.","Il protège Gotham la nuit.","Le justicier chauve-souris, Bruce Wayne."]},
      { name:"Harry Potter", alt:["Harry"], clues:["Il est orphelin.","Il vit sous un escalier.","Il a une cicatrice au front.","Il étudie à Poudlard.","Le sorcier à lunettes qui a survécu."]},
      { name:"La Lune", alt:["Lune"], clues:["On la voit surtout la nuit.","Elle change de forme selon les jours.","Elle contrôle les marées.","Neil Armstrong y a marché en 1969.","Le satellite naturel de la Terre."]},
      { name:"Zidane", alt:["Zinédine Zidane","Zizou"], clues:["Il est né à Marseille.","C'est une légende du sport français.","Il a marqué deux fois en finale en 1998.","Son coup de tête en 2006 est resté célèbre.","Zizou, numéro 10 des Bleus."]},
      { name:"Dracula", alt:["Comte Dracula"], clues:["Il vit dans un château.","Il ne sort jamais en journée.","Il dort dans un cercueil.","Il craint l'ail et les croix.","Le vampire de Transylvanie."]},
      { name:"Astérix", alt:[], clues:["Il est petit mais malin.","Il vit dans un village qui résiste.","Son meilleur ami est très costaud.","Il boit de la potion magique.","Le Gaulois à moustache blonde et casque ailé."]},
      { name:"Titanic", alt:["Le Titanic"], clues:["Il était réputé indestructible.","Il a fait naufrage en 1912.","Un iceberg l'a coulé.","Jack et Rose sont à son bord au cinéma.","Le paquebot le plus célèbre de l'histoire."]},
      { name:"Cléopâtre", alt:["Cleopatre"], clues:["C'est une reine de l'Antiquité.","Elle a séduit deux Romains puissants.","Elle règne sur l'Égypte.","Un serpent aurait causé sa mort.","La dernière pharaonne, au nez célèbre."]},
      { name:"Minecraft", alt:[], clues:["Tout y est carré.","On y construit ce qu'on veut.","Les Creepers y explosent.","On y mine et on y craft.","Le jeu de cubes le plus vendu au monde."]},
    ],
  },
};
