/* Contenu des thèmes. Ajouter un thème = une entrée dans chaque section. */
window.THEMES = {
  meta: {
    lol:     { label: "League of Legends", emoji: "⚔️" },
    pokemon: { label: "Pokémon",           emoji: "🔴" },
    got:     { label: "Game of Thrones",   emoji: "🐉" },
    general: { label: "Général",           emoji: "🎲" },
  },

  /* Générations Pokémon (plages du Pokédex national). Noms FR + sprites récupérés à la volée. */
  pokemonGens: [
    { id: 1, label: "Gén 1 — Kanto",   from: 1,   to: 151 },
    { id: 2, label: "Gén 2 — Johto",   from: 152, to: 251 },
    { id: 3, label: "Gén 3 — Hoenn",   from: 252, to: 386 },
    { id: 4, label: "Gén 4 — Sinnoh",  from: 387, to: 493 },
    { id: 5, label: "Gén 5 — Unys",    from: 494, to: 649 },
    { id: 6, label: "Gén 6 — Kalos",   from: 650, to: 721 },
    { id: 7, label: "Gén 7 — Alola",   from: 722, to: 809 },
    { id: 8, label: "Gén 8 — Galar",   from: 810, to: 905 },
    { id: 9, label: "Gén 9 — Paldea",  from: 906, to: 1025 },
  ],

  /* ── QUI EST-CE : pools de personnages ── */
  quiestce: {
    lol: {
      kind: "ddragon",
      chars: ["Ahri","Akali","Amumu","Annie","Ashe","Blitzcrank","Braum","Caitlyn","Camille","Darius","Diana","Draven",
        "Ekko","Elise","Ezreal","Fiora","Fizz","Galio","Garen","Gragas","Graves","Irelia","Ivern","Janna","Jax","Jayce",
        "Jhin","Jinx","Karma","Karthus","Katarina","Kayle","Kayn","Kennen","Leona","Lissandra","Lucian","Lulu","Lux",
        "Malphite","Malzahar","Maokai","Mordekaiser","Morgana","Nami","Nasus","Nautilus","Neeko","Nidalee","Nocturne",
        "Olaf","Orianna","Pantheon","Poppy","Pyke","Quinn","Rakan","Rammus","Rengar","Riven","Rumble","Ryze","Samira",
        "Sejuani","Senna","Seraphine","Shen","Shyvana","Singed","Sion","Sivir","Skarner","Sona","Soraka","Swain","Sylas",
        "Syndra","Talon","Taric","Teemo","Thresh","Tristana","Tryndamere","Twitch","Urgot","Varus","Vayne","Veigar","Vi",
        "Viego","Viktor","Vladimir","Volibear","Xayah","Xerath","Yasuo","Yone","Yorick","Yuumi","Zac","Zed","Ziggs",
        "Zilean","Zoe","Zyra"],
    },
    pokemon: { kind: "pokeapi" },
    got: {
      kind: "wiki",
      chars: [
        ["Jon Snow","Jon Snow"],["Daenerys Targaryen","Daenerys Targaryen"],["Tyrion Lannister","Tyrion Lannister"],
        ["Cersei Lannister","Cersei Lannister"],["Jaime Lannister","Jaime Lannister"],["Arya Stark","Arya Stark"],
        ["Sansa Stark","Sansa Stark"],["Bran Stark","Bran Stark"],["Eddard Stark","Eddard Stark"],
        ["Catelyn Stark","Catelyn Stark"],["Robb Stark","Robb Stark"],["Joffrey Baratheon","Joffrey Baratheon"],
        ["Stannis Baratheon","Stannis Baratheon"],["Robert Baratheon","Robert Baratheon"],["Melisandre","Mélisandre"],
        ["Davos Mervault","Davos Mervault"],["Brienne de Torth","Brienne de Torth"],["Sandor Clegane","Sandor Clegane"],
        ["Gregor Clegane","Gregor Clegane"],["Petyr Baelish","Petyr Baelish"],["Varys","Varys"],
        ["Samwell Tarly","Samwell Tarly"],["Jorah Mormont","Jorah Mormont"],["Khal Drogo","Khal Drogo"],
        ["Missandei","Missandei"],["Ver Gris","Ver Gris"],["Theon Greyjoy","Theon Greyjoy"],["Yara Greyjoy","Yara Greyjoy"],
        ["Ramsay Bolton","Ramsay Bolton"],["Roose Bolton","Roose Bolton"],["Tywin Lannister","Tywin Lannister"],
        ["Olenna Tyrell","Olenna Tyrell"],["Margaery Tyrell","Margaery Tyrell"],["Loras Tyrell","Loras Tyrell"],
        ["Hodor","Hodor"],["Gendry","Gendry"],["Bronn","Bronn (Le Trône de fer)"],["Podrick Payne","Podrick Payne"],
        ["Ygrid","Ygrid"],["Tormund","Tormund Fléau-d'Ogres"],["Le Roi de la Nuit","Roi de la Nuit"],
        ["Oberyn Martell","Oberyn Martell"],["Ellaria Sand","Ellaria Sand"],["Grand Mestre Pycelle","Pycelle"],
        ["Qyburn","Qyburn"],["Euron Greyjoy","Euron Greyjoy"],["Beric Dondarrion","Beric Dondarrion"],
        ["Jaqen H'ghar","Jaqen H'ghar"],["Viserys Targaryen","Viserys Targaryen"],["Renly Baratheon","Renly Baratheon"],
      ],
    },
    general: {
      kind: "wiki",
      chars: [
        ["Batman","Batman"],["Superman","Superman"],["Spider-Man","Spider-Man"],["Iron Man","Iron Man"],
        ["Thor","Thor (Marvel Comics)"],["Hulk","Hulk"],["Wonder Woman","Wonder Woman"],["Harry Potter","Harry Potter"],
        ["Hermione Granger","Hermione Granger"],["Ron Weasley","Ron Weasley"],["Albus Dumbledore","Albus Dumbledore"],
        ["Voldemort","Lord Voldemort"],["Gandalf","Gandalf"],["Frodon","Frodon Sacquet"],["Legolas","Legolas"],
        ["Dark Vador","Dark Vador"],["Yoda","Yoda"],["Luke Skywalker","Luke Skywalker"],["Han Solo","Han Solo"],
        ["Shrek","Shrek"],["Mario","Mario (personnage)"],["Luigi","Luigi"],["Sonic","Sonic (personnage)"],
        ["Lara Croft","Lara Croft"],["James Bond","James Bond"],["Sherlock Holmes","Sherlock Holmes"],
        ["Napoléon","Napoléon Ier"],["Cléopâtre","Cléopâtre VII"],["Albert Einstein","Albert Einstein"],
        ["Kylian Mbappé","Kylian Mbappé"],["Zinédine Zidane","Zinédine Zidane"],["Beyoncé","Beyoncé"],
        ["Michael Jackson","Michael Jackson"],["Astérix","Astérix"],["Obélix","Obélix"],["Tintin","Tintin"],
        ["Lucky Luke","Lucky Luke"],["Mickey Mouse","Mickey Mouse"],["Donald Duck","Donald Duck"],
        ["Homer Simpson","Homer Simpson"],["Bart Simpson","Bart Simpson"],["Bob l'éponge","Bob l'éponge"],
        ["Naruto","Naruto Uzumaki"],["Son Goku","Son Goku"],["Monkey D. Luffy","Monkey D. Luffy"],
        ["Elsa","Elsa (La Reine des neiges)"],["Simba","Simba"],["Buzz l'Éclair","Buzz l'Éclair"],
        ["Woody","Woody (Toy Story)"],["Jack Sparrow","Jack Sparrow"],["Père Noël","Père Noël"],
        ["Dracula","Dracula (personnage)"],["Mary Poppins","Mary Poppins (personnage)"],["Indiana Jones","Indiana Jones"],
        ["Rocky Balboa","Rocky Balboa"],["Terminator","Terminator (personnage)"],["Le Petit Prince","Le Petit Prince"],
        ["Titeuf","Titeuf"],["Marie Curie","Marie Curie"],["Léonard de Vinci","Léonard de Vinci"],
      ],
    },
  },

  /* ── IMPOSTEUR : paires de mots proches ── */
  imposteur: {
    lol: [["Garen","Darius"],["Yasuo","Yone"],["Ahri","LeBlanc"],["Zed","Talon"],["Lux","Morgana"],["Jinx","Vi"],
      ["Ezreal","Lucian"],["Blitzcrank","Thresh"],["Teemo","Kennen"],["Ashe","Varus"],["Leona","Diana"],
      ["Nasus","Renekton"],["Katarina","Akali"],["Amumu","Annie"],["Braum","Taric"],["Soraka","Sona"],
      ["Baron Nashor","Drake"],["Jungle","Toplane"],["Faille de l'invocateur","ARAM"],["Flash","Ghost"],
      ["Tourelle","Nexus"],["Sbire","Monstre épique"],["Pentakill","Quadrakill"],["Support","ADC"],
      ["Riven","Fiora"],["Malphite","Rammus"],["Veigar","Ziggs"],["Vayne","Twitch"],["Thresh","Nautilus"],
      ["Worlds","LEC"]],
    pokemon: [["Pikachu","Raichu"],["Ectoplasma","Spectrum"],["Ronflex","Goinfrex"],["Évoli","Aquali"],
      ["Dracaufeu","Dracolosse"],["Magicarpe","Poissirène"],["Miaouss","Persian"],["Rondoudou","Grodoudou"],
      ["Mewtwo","Mew"],["Onix","Steelix"],["Salamèche","Héricendre"],["Carapuce","Tortank"],
      ["Artikodin","Électhor"],["Caninos","Arcanin"],["Pokéball","Masterball"],["Sacha","Ondine"],
      ["Team Rocket","Ligue Pokémon"],["Pokédex","Pokéball"],["Bourg Palette","Argenta"],["Badge","CT"],
      ["Bulbizarre","Chetiflor"],["Nidoking","Nidoqueen"],["Léviator","Lokhlass"],["Métamorph","Ditto"],
      ["Pierre","Ondine"],["Centre Pokémon","Boutique Pokémon"],["Dresseur","Champion d'arène"],
      ["Type Feu","Type Eau"],["Méga-évolution","Gigamax"],["Shiny","Légendaire"]],
    got: [["Jon Snow","Robb Stark"],["Cersei","Margaery"],["Tyrion","Varys"],["Arya","Sansa"],
      ["La Montagne","Le Limier"],["Stannis","Renly"],["Stark","Lannister"],["Winterfell","Port-Réal"],
      ["Marcheurs Blancs","Sauvageons"],["Dothraki","Immaculés"],["Dragon","Loup géant"],["Le Mur","Le Trône de Fer"],
      ["Daenerys","Cersei"],["Jaime","Bronn"],["Mestre","Septon"],["Garde de Nuit","Garde Royale"],
      ["Valyria","Essos"],["Hodor","Ver Gris"],["Melisandre","Olenna"],["Baratheon","Targaryen"],
      ["Theon","Ramsay"],["Brienne","Podrick"],["Ygrid","Missandei"],["Acier valyrien","Verredragon"],
      ["Noces Pourpres","Noces Rouges"],["Corbeau","Raven"],["Peyredragon","Accalmie"],["Braavos","Meereen"],
      ["Joffrey","Tommen"],["Oberyn","Euron"]],
    general: [["Café","Thé"],["Croissant","Pain au chocolat"],["Vélo","Trottinette"],["Plage","Piscine"],
      ["Chien","Chat"],["Pizza","Tacos"],["Ski","Snowboard"],["Métro","Bus"],["Star Wars","Star Trek"],
      ["Harry Potter","Le Seigneur des Anneaux"],["Titanic","Avatar"],["Breaking Bad","Narcos"],
      ["Friends","How I Met Your Mother"],["Le Roi Lion","Le Livre de la Jungle"],["Mario","Sonic"],
      ["Minecraft","Fortnite"],["Noël","Nouvel An"],["Boulanger","Pâtissier"],["Guitare","Piano"],["Lune","Soleil"],
      ["Football","Rugby"],["Netflix","YouTube"],["Mariage","Anniversaire"],["Montagne","Campagne"],
      ["Médecin","Infirmier"],["Avion","Train"],["Bière","Vin"],["Barbecue","Raclette"],
      ["Camping","Hôtel"],["Permis de conduire","Bac"]],
  },

  /* ── QUIZ MYSTÈRE : 5 indices du plus vague au plus précis ── */
  quiz: {
    lol: [
      { name:"Teemo", alt:[], clues:["C'est un yordle.","Il porte un grand chapeau.","Tout le monde le déteste en face.","Il pose des champignons invisibles.","Le scout jaune de Bandle, cauchemar des toplaners."]},
      { name:"Yasuo", alt:[], clues:["C'est un épéiste.","Il vient d'Ionia.","Il a été accusé à tort d'un meurtre.","Son bouclier se recharge en bougeant et il maîtrise le vent.","Le samouraï exilé au mur de vent, frère de Yone."]},
      { name:"Jinx", alt:[], clues:["Elle vient de Zaun.","Elle est complètement folle.","Elle adore les explosions.","Sa sœur est une agente de Piltover.","La tireuse aux tresses bleues avec Pow-Pow et Fishbones."]},
      { name:"Thresh", alt:[], clues:["C'est un spectre.","Il vient des Îles Obscures.","Il collectionne les âmes dans sa lanterne.","Son crochet est redouté en botlane.","Le geôlier des âmes à la faux et à la lanterne."]},
      { name:"Lux", alt:["Luxanna"], clues:["Elle vient de Demacia.","Elle est très souriante.","Son frère est un grand soldat à la grosse épée.","Elle manie la lumière.","La mage lumineuse, sœur de Garen, au laser géant."]},
      { name:"Amumu", alt:[], clues:["Il est très triste.","C'est une momie.","Il cherche désespérément un ami.","Ses pleurs font des dégâts autour de lui.","La petite momie verte qui pleure, ultime en toile."]},
      { name:"Blitzcrank", alt:[], clues:["C'est un robot.","Il a été créé à Zaun.","Il est fait de vapeur et de métal.","Son bras se tend pour attraper les ennemis.","Le golem de vapeur doré au grab légendaire."]},
      { name:"Darius", alt:[], clues:["Il vient de Noxus.","C'est un général redouté.","Son frère lance des haches lui aussi.","Il saigne ses ennemis avant de les achever.","La Main de Noxus et sa guillotine."]},
      { name:"Ahri", alt:[], clues:["Elle vient d'Ionia.","Elle a neuf queues.","Elle charme ses ennemis.","C'est une renarde qui absorbe l'essence vitale.","La renarde à neuf queues et son baiser charmeur."]},
      { name:"Ezreal", alt:[], clues:["C'est un explorateur.","Il vient de Piltover.","Il est très sûr de lui.","Son gantelet tire des projectiles magiques.","L'aventurier blond qui spamme son Q et blink partout."]},
      { name:"Yuumi", alt:[], clues:["C'est un familier magique.","Elle voyage sur un livre.","Elle s'attache à un allié.","Impossible de la cibler quand elle est fixée.","La chatte magique qui AFK sur son support."]},
      { name:"Garen", alt:[], clues:["Il vient de Demacia.","Il crie le nom de son royaume.","Sa sœur manie la lumière.","Il tourne sur lui-même avec sa grande épée.","Le soldat au E qui spin et à l'ultime justicier."]},
      { name:"Nasus", alt:[], clues:["Il est très ancien.","Il vient du désert de Shurima.","Il a une tête d'animal.","Son bâton devient plus fort à chaque sbire tué.","Le gardien à tête de chacal et son Q infini."]},
      { name:"Zed", alt:[], clues:["Il vient d'Ionia.","Il maîtrise une magie interdite.","Il crée des ombres qui le copient.","C'est le maître de l'Ordre des Ombres.","L'assassin masqué rouge et noir aux shurikens."]},
      { name:"Braum", alt:[], clues:["Il est très costaud.","Il vient du Freljord.","Il a une immense moustache.","Son bouclier bloque les projectiles pour toute l'équipe.","Le cœur du Freljord et sa porte de glace."]},
      { name:"Katarina", alt:[], clues:["Elle vient de Noxus.","Elle a les cheveux roux.","Elle a une cicatrice sur le visage.","Elle se téléporte de dague en dague.","La lame sinistre et son ultime tourbillon de couteaux."]},
    ],
    pokemon: [
      { name:"Ronflex", alt:[], clues:["Type Normal.","Il est énorme et très lourd.","Il passe sa vie à manger et dormir.","Il bloque la route dans les jeux, il faut une flûte pour le réveiller.","Le gros dormeur bleu-vert au ventre crème."]},
      { name:"Ectoplasma", alt:[], clues:["Il est violet.","Type Spectre et Poison.","Il adore faire des farces effrayantes dans l'ombre.","C'est l'évolution finale de Fantominus.","Le fantôme au sourire immense et aux yeux rouges."]},
      { name:"Pikachu", alt:[], clues:["Type Électrik.","Il vit en groupe dans les forêts.","Ses joues stockent de l'électricité.","C'est le compagnon de Sacha dans le dessin animé.","La souris jaune, mascotte de la licence."]},
      { name:"Dracaufeu", alt:[], clues:["Il peut voler.","Type Feu.","La flamme de sa queue reflète sa vitalité.","C'est l'évolution finale d'un starter de Kanto.","Le dragon orange, starter feu de la première génération."]},
      { name:"Magicarpe", alt:[], clues:["Type Eau.","Il est réputé complètement inutile.","Il ne sait quasiment que faire Trempette.","Il évolue en un dragon marin redoutable.","Le poisson rouge et or qui saute partout."]},
      { name:"Léviator", alt:[], clues:["Il est immense.","Type Eau et Vol.","Il est connu pour sa rage destructrice.","Il évolue d'un Pokémon considéré comme le plus faible.","Le serpent de mer bleu issu de Magicarpe."]},
      { name:"Évoli", alt:[], clues:["Type Normal.","Son code génétique est instable.","Il peut évoluer de nombreuses façons différentes.","Ses évolutions incluent Aquali, Voltali et Pyroli.","Le petit renard marron aux multiples évolutions."]},
      { name:"Mewtwo", alt:[], clues:["Type Psy.","Il a été créé par des scientifiques.","C'est un clone surpuissant d'un Pokémon mythique.","On l'affronte dans une grotte après la Ligue.","Le clone légendaire de Mew."]},
      { name:"Psykokwak", alt:[], clues:["Type Eau.","Il a constamment mal à la tête.","Ses migraines libèrent des pouvoirs psychiques.","Dans le dessin animé, il sort sans arrêt de la Pokéball d'Ondine.","Le canard jaune qui se tient la tête."]},
      { name:"Rondoudou", alt:[], clues:["Il est rose.","Type Normal et Fée.","Sa voix endort quiconque l'écoute.","Il se venge en dessinant sur le visage des endormis.","La boule rose qui chante avec son micro-feutre."]},
      { name:"Métamorph", alt:["Metamorph","Ditto"], clues:["Type Normal.","Il est rose et informe.","Il peut se transformer en n'importe quoi.","Il est très recherché pour la reproduction.","La flaque rose qui copie tous les Pokémon."]},
      { name:"Lokhlass", alt:[], clues:["Type Eau et Glace.","Il est d'une grande douceur.","Il transporte les gens sur son dos à travers les mers.","On l'utilise souvent comme Surf-taxi.","Le plésiosaure bleu à carapace grise."]},
      { name:"Carapuce", alt:[], clues:["Type Eau.","Il a une carapace.","C'est un Pokémon de départ.","Il évolue en Carabaffe puis en Tortank.","La petite tortue bleue, starter eau de Kanto."]},
      { name:"Salamèche", alt:[], clues:["Type Feu.","Il a une flamme au bout de la queue.","C'est un Pokémon de départ.","Il évolue en Reptincel puis en Dracaufeu.","Le petit lézard orange, starter feu de Kanto."]},
      { name:"Miaouss", alt:[], clues:["Type Normal.","Il adore les objets brillants.","Une pièce dorée orne son front.","Dans le dessin animé, il parle et suit la Team Rocket.","Le chat beige de la Team Rocket."]},
      { name:"Onix", alt:[], clues:["Il vit sous terre.","Type Roche et Sol.","Son corps est une chaîne de rochers gigantesque.","C'est le Pokémon emblématique de Pierre.","Le serpent de pierre géant."]},
    ],
    got: [
      { name:"Jon Snow", alt:["Jon"], clues:["Il vient du Nord.","On le dit bâtard.","Il rejoint la Garde de Nuit.","Son loup géant s'appelle Fantôme.","Le corbeau devenu roi du Nord, « You know nothing »."]},
      { name:"Tyrion", alt:["Tyrion Lannister"], clues:["Il est très intelligent.","Sa famille est la plus riche de Westeros.","Il boit et il sait des choses.","Son père le méprise, sa sœur le hait.","Le nain Lannister, Main de la Reine."]},
      { name:"Daenerys", alt:["Khaleesi","Dany","Daenerys Targaryen"], clues:["Elle vient d'une dynastie déchue.","Elle traverse le Détroit depuis Essos.","Elle épouse un chef de guerre nomade.","Le feu ne la brûle pas.","La Mère des Dragons, Khaleesi."]},
      { name:"Arya", alt:["Arya Stark"], clues:["C'est une jeune fille du Nord.","Elle refuse d'être une lady.","Elle dresse une liste de noms.","Elle apprend auprès des Sans-Visage.","La petite Stark à l'épée Aiguille."]},
      { name:"Le Limier", alt:["Sandor","Sandor Clegane","Limier"], clues:["C'est un guerrier redoutable.","Il a peur du feu.","Son visage est à moitié brûlé.","Son frère est encore plus monstrueux que lui.","Sandor Clegane, protecteur bougon d'Arya."]},
      { name:"Hodor", alt:[], clues:["Il est immense et doux.","Il sert la famille Stark.","Il ne dit qu'un seul mot.","Il porte Bran sur son dos.","« Hold the door »."]},
      { name:"Cersei", alt:["Cersei Lannister"], clues:["Elle est reine.","Elle aime le vin.","Elle aime son frère jumeau… beaucoup.","Elle fait exploser un septuaire entier.","La reine Lannister, mère de Joffrey."]},
      { name:"Jaime", alt:["Jaime Lannister"], clues:["C'est l'un des meilleurs épéistes du royaume.","On l'appelle un tueur de roi.","Il perd sa main d'épée.","Il pousse un enfant par une fenêtre.","Le Régicide, jumeau de Cersei."]},
      { name:"Ned Stark", alt:["Ned","Eddard","Eddard Stark"], clues:["Il est loyal et honorable.","Il gouverne le Nord.","Il devient Main du Roi malgré lui.","Son honneur lui coûte la tête dès la saison 1.","Le seigneur de Winterfell, père de la meute."]},
      { name:"Le Roi de la Nuit", alt:["Roi de la Nuit","Night King"], clues:["Il vient du Grand Nord.","Il ne parle jamais.","Il relève les morts.","Il tue un dragon d'un seul javelot.","Le chef des Marcheurs Blancs aux yeux bleus."]},
      { name:"Brienne", alt:["Brienne de Torth","Brienne de Tarth"], clues:["C'est une guerrière d'exception.","On se moque de son apparence.","Elle jure de protéger les filles Stark.","Elle est adoubée par Jaime.","La chevaleresse de Torth, fidèle entre toutes."]},
      { name:"Samwell", alt:["Sam","Samwell Tarly"], clues:["Il est peureux et maladroit.","Son père le renie.","Il rejoint la Garde de Nuit avec Jon.","Il tue un Marcheur Blanc avec du verredragon.","Le meilleur ami de Jon, apprenti mestre."]},
      { name:"Joffrey", alt:["Joffrey Baratheon"], clues:["Il est très jeune.","Tout le monde le déteste.","Il est cruel et lâche.","Il ordonne l'exécution de Ned Stark.","Le roi blond empoisonné à son propre mariage."]},
      { name:"Petyr Baelish", alt:["Littlefinger","Baelish","Petyr"], clues:["Il est très manipulateur.","Il gère les finances du royaume.","Il tient des maisons closes.","« Le chaos est une échelle ».","Littlefinger, l'homme au surnom d'oiseau."]},
      { name:"Theon", alt:["Theon Greyjoy"], clues:["Il a grandi loin de sa vraie famille.","Il vient des îles de Fer.","Il trahit ceux qui l'ont élevé.","Ramsay le torture et le rebaptise Schlingue.","Le Greyjoy déchu, pupille des Stark."]},
      { name:"Melisandre", alt:["Mélisandre","La femme rouge"], clues:["Elle vient d'Essos.","Elle porte toujours du rouge.","Elle voit l'avenir dans les flammes.","Elle sert le Maître de la Lumière.","La prêtresse rouge au collier magique."]},
    ],
    general: [
      { name:"Le Père Noël", alt:["Père Noël","Papa Noël","Santa"], clues:["Il travaille une seule nuit par an.","Il est très généreux.","Il s'habille en rouge.","Il passe par la cheminée.","Ho ho ho, il vit au pôle Nord."]},
      { name:"La Joconde", alt:["Joconde","Mona Lisa"], clues:["Elle est italienne.","Elle est mondialement célèbre.","Son sourire est mystérieux.","Elle vit au Louvre.","Le tableau de Léonard de Vinci."]},
      { name:"Napoléon", alt:["Napoléon Bonaparte","Bonaparte"], clues:["Il est né en Corse.","Il devient empereur.","Il gagne Austerlitz.","Il finit exilé à Sainte-Hélène.","Le petit caporal au bicorne."]},
      { name:"Batman", alt:[], clues:["Il est très riche.","Il a perdu ses parents.","Il n'a aucun super-pouvoir.","Il protège Gotham la nuit.","Le justicier chauve-souris, Bruce Wayne."]},
      { name:"Harry Potter", alt:["Harry"], clues:["Il est orphelin.","Il vit sous un escalier.","Il a une cicatrice au front.","Il étudie à Poudlard.","Le sorcier à lunettes qui a survécu."]},
      { name:"La Lune", alt:["Lune"], clues:["On la voit surtout la nuit.","Elle change de forme selon les jours.","Elle contrôle les marées.","Neil Armstrong y a marché en 1969.","Le satellite naturel de la Terre."]},
      { name:"Zidane", alt:["Zinédine Zidane","Zizou"], clues:["Il est né à Marseille.","C'est une légende du sport français.","Il a marqué deux fois en finale en 1998.","Son coup de tête en 2006 est resté célèbre.","Zizou, numéro 10 des Bleus."]},
      { name:"Dracula", alt:["Comte Dracula"], clues:["Il vit dans un château.","Il ne sort jamais en journée.","Il dort dans un cercueil.","Il craint l'ail et les croix.","Le vampire de Transylvanie."]},
      { name:"Astérix", alt:[], clues:["Il est petit mais malin.","Il vit dans un village qui résiste.","Son meilleur ami est très costaud.","Il boit de la potion magique.","Le Gaulois à moustache blonde et casque ailé."]},
      { name:"Titanic", alt:["Le Titanic"], clues:["Il était réputé indestructible.","Il a fait naufrage en 1912.","Un iceberg l'a coulé.","Jack et Rose sont à son bord au cinéma.","Le paquebot le plus célèbre de l'histoire."]},
      { name:"Cléopâtre", alt:["Cleopatre"], clues:["C'est une reine de l'Antiquité.","Elle a séduit deux Romains puissants.","Elle règne sur l'Égypte.","Un serpent aurait causé sa mort.","La dernière pharaonne, au nez célèbre."]},
      { name:"Minecraft", alt:[], clues:["Tout y est carré.","On y construit ce qu'on veut.","Les Creepers y explosent.","On y mine et on y craft.","Le jeu de cubes le plus vendu au monde."]},
      { name:"La Tour Eiffel", alt:["Tour Eiffel"], clues:["Elle est en fer.","Elle devait être temporaire.","Elle scintille chaque soir.","Elle a été construite pour l'Expo de 1889.","La dame de fer du Champ-de-Mars."]},
      { name:"Shrek", alt:[], clues:["Il est vert.","Il vit dans un marais.","Il déteste qu'on le dérange.","Son meilleur ami est un âne bavard.","L'ogre qui épouse Fiona."]},
      { name:"Einstein", alt:["Albert Einstein"], clues:["Il est né en Allemagne.","Il a les cheveux en bataille.","Il a reçu le prix Nobel.","E = mc².","Le père de la relativité, à la langue tirée."]},
      { name:"Le Roi Lion", alt:["Roi Lion","Simba"], clues:["Ça se passe en Afrique.","Un oncle y trahit son frère.","Il y a un phacochère et un suricate.","Hakuna Matata.","Le dessin animé Disney avec Simba et Mufasa."]},
    ],
  },
};
